// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Task suggestion AI agent.
 *
 * - suggestTasks - A function that suggests tasks based on user goals, time, and habits.
 * - SuggestTasksInput - The input type for the suggestTasks function.
 * - SuggestTasksOutput - The return type for the suggestTasks function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTasksInputSchema = z.object({
  goals: z
    .string()
    .describe('The user specified goals.'),
  availableTime: z.string().describe('The time available for tasks.'),
  pastHabits: z.string().describe("The user's past habits."),
});
export type SuggestTasksInput = z.infer<typeof SuggestTasksInputSchema>;

const SuggestTasksOutputSchema = z.object({
  suggestedTasks: z
    .array(z.string())
    .describe('An array of suggested tasks based on the input.'),
});
export type SuggestTasksOutput = z.infer<typeof SuggestTasksOutputSchema>;

export async function suggestTasks(input: SuggestTasksInput): Promise<SuggestTasksOutput> {
  return suggestTasksFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTasksPrompt',
  input: {schema: SuggestTasksInputSchema},
  output: {schema: SuggestTasksOutputSchema},
  prompt: `Based on the user's goals, available time, and past habits, suggest a list of tasks.

Goals: {{{goals}}}
Available Time: {{{availableTime}}}
Past Habits: {{{pastHabits}}}

Suggest tasks that align with the user's goals and can be completed within the available time, considering their habits.
Return a list of tasks in an array.

Tasks:`,
});

const suggestTasksFlow = ai.defineFlow(
  {
    name: 'suggestTasksFlow',
    inputSchema: SuggestTasksInputSchema,
    outputSchema: SuggestTasksOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
